_wandb:
    value:
        cli_version: 0.25.0
        e:
            fk0a5drqd2uh00httirwutztqe25w8ev:
                codePath: /home/krzychu/Pulpit/PROGRAMOWANIE/AI/AICup/training/experiment_hub.ipynb
                codePathLocal: experiment_hub.ipynb
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "491104411648"
                        used: "232888270848"
                executable: /home/krzychu/miniconda3/envs/AICup/bin/python
                git:
                    commit: f617c01e511c042fb6c7a8821fb1ed2328c85b14
                    remote: https://github.com/Arkantanti/AICup.git
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 1024
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-c9d03641-e4e0-573b-6dc6-9cf7751a668b
                host: krzychu-Legion
                memory:
                    total: "33569890304"
                os: Linux-6.14.0-33-generic-x86_64-with-glibc2.39
                program: /home/krzychu/Pulpit/PROGRAMOWANIE/AI/AICup/training/experiment_hub.ipynb
                python: CPython 3.10.19
                root: /home/krzychu/Pulpit/PROGRAMOWANIE/AI/AICup/training
                startedAt: "2026-03-04T19:45:38.442770Z"
                writerId: fk0a5drqd2uh00httirwutztqe25w8ev
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 5
                - 6
                - 53
            "2":
                - 5
                - 6
                - 53
            "3":
                - 2
                - 16
            "4": 3.10.19
            "5": 0.25.0
            "8":
                - 1
            "12": 0.25.0
            "13": linux-x86_64
feature_version:
    value:
        - airspeed
        - min_z
        - max_z
        - size_Flock
        - size_Large bird
        - size_Medium bird
        - size_Small bird
        - duration
        - avg_rcs
        - std_rcs
        - min_rcs
        - max_rcs
        - height_fluctuation
        - latitude_fluctuation
        - longitude_fluctuation
        - local_2d_circularity_max
        - local_3d_circularity_mean
params:
    value:
        early_stopping_rounds: 50
        learning_rate: 0.05
        max_depth: 6
        n_estimators: 1000
        num_class: 9
        objective: multi:softprob
        random_state: 42
        tree_method: hist
        use_weights: true
